$: << File.dirname(__FILE__)

require 'set'

require 'hypothesis-engine/core_additions'

require 'hypothesis-engine/runner'
require 'hypothesis-engine/game'
require 'hypothesis-engine/profile'
require 'hypothesis-engine/ui'
require 'hypothesis-engine/config'
#require 'hypothesis-engine/player_generator'
require 'hypothesis-engine/level_loader'
#require 'hypothesis-engine/tower'
require 'hypothesis-engine/level'
#require 'hypothesis-engine/turn'
require 'hypothesis-engine/floor'
#require 'hypothesis-engine/space'
#require 'hypothesis-engine/position'

#require 'ruby_warrior/units/base'
#require 'ruby_warrior/units/warrior'
#require 'ruby_warrior/units/sludge'
#require 'ruby_warrior/units/archer'
#require 'ruby_warrior/units/thick_sludge'
#require 'ruby_warrior/units/captive'
#require 'ruby_warrior/units/wizard'
#require 'ruby_warrior/units/golem'

#require 'ruby_warrior/abilities/base'
#require 'ruby_warrior/abilities/walk'
#require 'ruby_warrior/abilities/attack'
#require 'ruby_warrior/abilities/feel'
#require 'ruby_warrior/abilities/rest'
#require 'ruby_warrior/abilities/health'
#require 'ruby_warrior/abilities/look'
#require 'ruby_warrior/abilities/shoot'
#require 'ruby_warrior/abilities/rescue'
#require 'ruby_warrior/abilities/pivot'
#require 'ruby_warrior/abilities/distance_of'
#require 'ruby_warrior/abilities/bind'
#require 'ruby_warrior/abilities/listen'
#require 'ruby_warrior/abilities/direction_of_stairs'
#require 'ruby_warrior/abilities/direction_of'
#require 'ruby_warrior/abilities/explode'
#require 'ruby_warrior/abilities/detonate'
#require 'ruby_warrior/abilities/form'
